### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by aomv** [bootphon/phonemizer#10]
Hey,

 Do you know if there is a c++ or equivalent version of this project?

thank you

**Comment by mmmaat** [comment]
Hi,

I do not know an equivalent in C++. But the phonemizer is just a wrapper on festival and espeak/espeak-ng, with some little post-processing. So you can probably use directly [espeak-ng](https://github.com/espeak-ng/espeak-ng), which is coded in C. In that case you will have to reimplement the post-processing in [this for loop](https://github.com/bootphon/phonemizer/blob/master/phonemizer/espeak.py#L86)

Mathieu
