### ISSUE TITLE
fatal error: language "mb-fr4" is not supported by the espeak-mbrola backend

### ISSUE THREAD

**Issue by sravani40** [bootphon/phonemizer#100]
echo "bonjour le monde" | phonemize -b espeak-mbrola -l mb-fr1 -p ' ' -w '/w '   when running this command it is giving error

fatal error: language "mb-fr4" is not supported by the espeak-mbrola backend

**Comment by hadware** [comment]
Did you properly install `mbrola-fr4`? Could you give us a bit more detail on your environment?

**Comment by mmmaat** [comment]
Not enough details, assuming it is an environment issue, closing.
