### ISSUE TITLE
The punctuation mark is not separated correctly when using space as the phone separator in v0.3.1

### ISSUE THREAD

**Issue by kan-bayashi** [bootphon/phonemizer#104]
Thank you for developing a great tool.
This is very useful to develop our speech processing toolkit.
I found unexpected behavior in v0.3.1.

**Describe the bug**
The punctuation mark is not separated correctly when using space as the phone separator.

**Phonemizer version**
- 0.3.1

**System**

- OS information: `Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019 x86_64`
- python version: `3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0]`

**To reproduce**
```python
from phonemizer import phonemize
from phonemizer.separator import Separator

text = "Hello, world."
separator = Separator(
    word=None,
    syllable=None,
    phone=" ",
)
phn = phonemize(text, separator=separator, preserve_punctuation=True)
print(phn)
```

**Expected behavior**
In phonemizer==0.3 (expected)
```bash
$ python test_phonemizer.py
h ə l oʊ , w ɜː l d .
```

In phonemizer==0.3.1 (seems wrong)
```bash
$ python test_phonemizer.py
h ə l oʊ, w ɜː l d.
```

**Comment by mmmaat** [comment]
in `phonemizer-3.2.1`this have been fixed by #119, the result is now `h ə l oʊ ,w ɜː l d .`, which is what is expected.
