### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by kofcio94** [bootphon/phonemizer#11]
```
$ python setup.py build
Traceback (most recent call last):
File "setup.py", line 20, in <module>
from setuptools import setup, find_packages
ImportError: No module named setuptools
```
I use ubuntu with preinstalled python version _Python 2.7.15rc1_

**Comment by mmmaat** [comment]
Try `sudo apt-get install python-setuptools`. If this fails, have a `pip install -U pip setuptools ` (eventually preceded by a `sudo`).

**Comment by kofcio94** [comment]
Thank you! It works. Also works after updating python to 3.6.5.

**Comment by mmmaat** [comment]
You're welcome ;)
