### ISSUE TITLE
how to get list of all phone of one language 

### ISSUE THREAD

**Issue by thanhlong1997** [bootphon/phonemizer#118]
Hi, thank for amazing repo. I am trying to get all phone in vietnames but i can't see how to do that in tutorial. Now i am using vietnamese 
large text corpus to collect a list of phone but i afraid it won't me enough. 
Pls help me how to get all phone in vietnamese language.

thank you so much

**Comment by mmmaat** [comment]
Hi, this is not possible with phonemizer. The list of phones comes from espeak-ng rules. You can inspect them by hand. Start [here](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/vi_list) and [here](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/vi_rules).
