### ISSUE TITLE
Phonemizer does not work with language="en"

### ISSUE THREAD

**Issue by Rishabh-Choudhry** [bootphon/phonemizer#130]
**Describe the bug**

I am trying to run the following code:

`from phonemizer.phonemize import phonemize

phonemize("apples",language="en"))`

But I get the following error:

> RuntimeError: language "en" is not supported by the espeak backend

How can I get the British english language running on phonemize function?

**Phonemizer version**
v3.2.1

**System**
Linux

**Comment by Rishabh-Choudhry** [comment]
Apologies for raising the issue. I figured it out. We can use the following code:

`phonemize("apples",language="en-gb"))`

**Comment by cbjrobertson** [comment]
Documenting this somewhere might be useful, as it doesn't comply with the espeak language [codes](https://github.com/espeak-ng/espeak-ng/blob/master/docs/languages.md).
