### ISSUE TITLE
Where/How to get a full list of phone set used for each language?

### ISSUE THREAD

**Issue by XuesongYang** [bootphon/phonemizer#131]
Thank you for the great tool. I am using it to make a G2P-like conversion. But I did not find what kind of complete list of phone set is used. I know the backend engine, like espeak, pre-defined such a phone set. I wonder if we could get it through phonemizer directly. Thanks.

**Comment by mmmaat** [comment]
Hi, indeed the explicit list of phonemes is not provided. For espeak this seems to be stored in a specific file for each language. inside the `phsource` folder ([for French here](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/ph_french)). Should not be too hard to write a parser for that file format for the extraction of the phonemes list.
