### ISSUE TITLE
tie option only compatible with espeak>=1.49

### ISSUE THREAD

**Issue by kylefoley76** [bootphon/phonemizer#135]
I'm getting the rror message

tie option only compatible with espeak>=1.49

but according to my research here

http://espeak.sourceforge.net/test/latest.html

1.48 is the latest version.

Also, brew install downloads 1.48

**Comment by mmmaat** [comment]
Indeed the latest espeak "old" is 1.48. Replaced by [espeak-ng](https://github.com/espeak-ng/espeak-ng) (new generation). On macos you have to compile it from source I guess : https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md#linux-mac-bsd
