### ISSUE TITLE
Manual placement of stresses

### ISSUE THREAD

**Issue by JoanisTriandafilidi** [bootphon/phonemizer#139]
Hey guys, two years ago you said that there is no way to set accents manually. How are things now? I tried to come up with something using the parameters of the phonemizer, but did not get what I wanted.

**Comment by mmmaat** [comment]
Hi, indeed this is not implemented, and we have no plan to do it. The only stuff `phonemizer`can do is to preserve or remove the stresses given by `espeak` backend.

If you (or someone else) want to contribute to the project by implementing such a feature, please propose a Pull Request, or reopen this issue to open a discussion. Thanks.
