### ISSUE TITLE
instructions for docker users

### ISSUE THREAD

**Issue by alecristia** [bootphon/phonemizer#14]
How does one access one's files from inside the interactive session? That is, if I `sudo docker run -it phonemizer /bin/bash` I get transported inside a different space, where my files are not available. Right? And this is the only way to call phonemizer in mac?

Minor suggestion: In the instructions for docker users, add the explicit instruction to do git clone https://github.com/bootphon/phonemizer.git.

**Comment by mmmaat** [comment]
You can use phonemizer directly in mac if you have espeak and/or festival installed in it. Else, yes, docker is the alternative.

To share data to/from docker use the -v option of *docker run*. 

`sudo docker run -v /path:/path/in/container -it phonemizer /bin/bash` mounts the host directory `/path` at the `/path/in/container`

**Comment by alecristia** [comment]
Thank you!

FYI, I'm getting this:


espeak: unrecognized option `--sep=_'

**Comment by mmmaat** [comment]
Within the docker ??

**Comment by mmmaat** [comment]
Can I have your espeak version please? 
`espeak --version`

**Comment by alecristia** [comment]
speak text-to-speech: 1.48.03  04.Mar.14   Data at: /usr/local/Cellar/espeak/1.48.04_1/share/espeak-dat

**Comment by mmmaat** [comment]
Solved in https://github.com/bootphon/phonemizer/commit/332b8dd8bb399e16fce025c4eaa95d9e21da45bf. Should be working now.
