### ISSUE TITLE
maybe wrong IPA symbol for a German word "aneinander"

### ISSUE THREAD

**Issue by XuesongYang** [bootphon/phonemizer#142]
**Describe the bug**
there is `/1/` appearing in the phonetic transcription.
```
$ echo "aneinander" | phonemize -l de -b espeak --with-stress
ˌan1aɪnˈandɜ
```

**Phonemizer version**
```
$ phonemize --version
phonemizer-3.2.1
available backends: espeak-ng-1.50, espeak-mbrola, festival-2.5.0, segments-2.2.1
```

**System**
Your OS (Linux distribution, Windows, ...), eventually Python version.

**To reproduce**
A short example (Python script or command) reproducing the bug.

**Expected behavior**

**Additional context**

**Comment by mmmaat** [comment]
Hi,

This is related to espeak, not phonemizer. Here its output compared to the one of `espeak-ng-1.50`:

```bash
$ echo "aneinander" | phonemize -l de -b espeak --with-stress
ˌan1aɪnˈandɜ
$ echo "aneinander" | espeak-ng -qx --ipa -v de
ˌan1aɪnˈandɜ
```
So we have a strict equivalence. If you think this is a bug please forward it to the [espeak-ng repo](https://github.com/espeak-ng/espeak-ng/issues).
