### ISSUE TITLE
utf-8 Decode error

### ISSUE THREAD

**Issue by mbpictures** [bootphon/phonemizer#148]
**Describe the bug**
I got an "utf8" decode error after phonemizing some text. The text I phonemized wasn't special (it contained an apostroph). The exception raised in the text_to_phonemes method of the EspeakWrapper in this line:
result.append(phonemes.decode())

**Phonemizer version**
phonemizer-3.2.1
available backends: espeak-ng-1.52, segments-2.2.1
uninstalled backends: espeak-mbrola, festival

**System**
Windows 11 64 Bit
Python 3.9

**To reproduce**
Call the phonemize method with some text and default parameters

**Expected behavior**
Correct decoded phonemes

**Additional context**
No additional context

**Comment by mmmaat** [comment]
Hi, please provide a canonical example with the exact input text and parameters you used.

**Comment by mmmaat** [comment]
closing as no extra info provided
