### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [bootphon/phonemizer#155]
Hi,
Would it be possible to change this license to MIT/ISC/LGPL so we can use this library in non-GPL software?
Thank you

**Comment by mmmaat** [comment]
Hi,
The phonemizer is linked on `espeak-ng`, which is GPL-3. So we have to keep that license.
Not really a link because we are in Python, but we are directly using the espeak shared library with CDLL in `/backend/espeak/api.py`.

**Comment by fakerybakery** [comment]
Ok, that makes sense. Thanks!
