### ISSUE TITLE
`ɾ` instead of `t` when phonemizing (?)

### ISSUE THREAD

**Issue by ai-tnc** [bootphon/phonemizer#157]
`Money is unlimited.`
gets transcribed to 
`mˈʌni ɪz ʌnlˈɪmɪɾᵻd.`

is the `ɾ` wrong or right? because i would expect a `t`.

`share it with an entrepreneur you know, share it on your social media, but`
is phonemized to
`ʃˈɛɹ ɪt wɪð ɐn ˌɑːntɹɪpɹənˈʊɹ juː nˈoʊ, ʃˈɛɹ ɪɾ ˌɔn jʊɹ sˈoʊʃəl mˈiːdiːə, bˌʌt`
the first "it" has a `t` while the second has the `ɾ`

wikipedia also lists `better` like `beɾɐ` but it seems odd
https://en.wikipedia.org/wiki/Voiced_dental_and_alveolar_taps_and_flaps

i'm not sure if this is a bug/inconsistency or valid way to phonemize.

on windows10 using the 1.51 install
[espeak-ng-X64.msi](https://github.com/espeak-ng/espeak-ng/releases/download/1.51/espeak-ng-X64.msi)

as well as on linux
`eSpeak text-to-speech: 1.48.15  16.Apr.15  Data at: /usr/lib/x86_64-linux-gnu/espeak-data`

**Comment by mmmaat** [comment]
Hi, this is an issue with espeak, not phonemizer. Try to install the [latest version](https://github.com/espeak-ng/espeak-ng/releases/tag/1.51) or submit your issue [here](https://github.com/espeak-ng/espeak-ng/issues).
