### ISSUE TITLE
how to get list of all phone of one language

### ISSUE THREAD

**Issue by ZhikangNiu** [bootphon/phonemizer#184]
**Is your feature request related to a problem? Please describe.**
I want to build a multilingual Text to Speech system and I need a phoneme vocabulary of one language.
Can phonemizer achieve this?
Actually I found a same issue https://github.com/bootphon/phonemizer/issues/118 and I check the lang_list and the phonemizer result don't same?
<img width="1197" alt="截屏2024-11-04 22 20 47" src="https://github.com/user-attachments/assets/422de67e-580a-4546-a457-9dd76a4cfbe7">
探	tan4
讨	tao3

**Comment by mmmaat** [comment]
Hi, as I said in #118 this is not possible to extract that using phonemizer.
