### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by abd-mhainy** [bootphon/phonemizer#19]
in this amazing library you are depending on espeak-ng and in thats library support Arabic language culd you please add this feature to your library

**Comment by mmmaat** [comment]
Hi, if you have installed espeak-ng Arabic is already available. To make sure of that try the following commands:
```
$ phonemize --version
phonemizer-1.0
available backends: festival-2.5.0, espeak-ng-1.49.2, segments-2.0.1
```
And
```
$ phonemize --help | grep Arabic
	ar	->	Arabic
```

**Comment by abd-mhainy** [comment]
how can install espeak-ng cause phonemize --version show only those backends
festival-2.5.0, espeak-1.48.03, segments-2.0.1

**Comment by mmmaat** [comment]
Follow instructions here: https://github.com/espeak-ng/espeak-ng/#linux-mac-bsd

**Comment by mmmaat** [comment]
Normally, the installation of espeak-ng will override the standard espeak.

**Comment by abd-mhainy** [comment]
do i need to clone the repository and if i have to where do i have to clone it is there a certain path or it dosent matter

**Comment by mmmaat** [comment]
Indeed you have to clone it (whatever the place, it will be installed as `/usr/local/bin/espeak-ng`), configure, compile and install it. Something like:
```
git clone https://github.com/espeak-ng/espeak-ng.git
cd espeak-ng
./configure
make
make install
```

**Comment by abd-mhainy** [comment]
thanks thats worked and now i can see arabic between the supported languages

**Comment by mmmaat** [comment]
Great ! Have fun :)

**Comment by abd-mhainy** [comment]
now it is giving:
fatal error: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

when i wrote the command as:
echo "السلام عليكم" | phonemize -l ar

**Comment by mmmaat** [comment]
I got that using python3:
```
$ echo "السلام عليكم" | phonemize -l ar
ʔassalaam ʕaliijkum 
```

I guess you are using python2 (have a `python --version` to make sure). I'm trying to find a fix. By now you can try to install it with python3. Just have a `python3 setup.py install`.

**Comment by mmmaat** [comment]
Ok I fixed it in that commit: https://github.com/bootphon/phonemizer/commit/532f9d24ed68f468bafb4b4d79c5ca0c212896b5. Should be working both in python2 and python3 now. Thanks for reporting that!

**Comment by abd-mhainy** [comment]
thanks a lot 
i will pull the last version

**Comment by abd-mhainy** [comment]
i made a pull but it is giving the same error 
my python version is 2.7

**Comment by abd-mhainy** [comment]
i think that i have to build again right

**Comment by abd-mhainy** [comment]
upgraded to python 3 and the problem has been solved 
thanks a lot for your help

**Comment by mmmaat** [comment]
Yes on python2 you have to pull AND to `python setup.py install` again.
