### ISSUE TITLE
add stress mark to phonemes

### ISSUE THREAD

**Issue by vcjob** [bootphon/phonemizer#24]
Hello everyone!

Just wondering if it's possible to add somehow stress mark to the sentence phonemized?
I mean, not asking backend (e.g. eSpeak) to add that, but not removing it instead. 
E.G. (if consider '+' as a stress mark) echo "hello world" | phonemize
              $  həloʊ wɜːld
      echo "hello+ wo+rld" | phonemize
              $  həlo+ʊ wɜː+ld
It would be just awesome, especially for languages like Russian.

**Comment by mmmaat** [comment]
Hello!

Well... actually the stresses are removed (https://github.com/bootphon/phonemizer/blob/master/phonemizer/backend.py#L268). I can add an option `--stress <char>` to the espeak backend, will be easy to do.

I'm working on the next release of phonemizer, dealing with language switch, so I'm adding the stresses on my todo list :)

**Comment by vcjob** [comment]
> Hello!
> 
> Well... actually the stresses are removed (https://github.com/bootphon/phonemizer/blob/master/phonemizer/backend.py#L268). I can add an option `--stress <char>` to the espeak backend, will be easy to do.
> 
> I'm working on the next release of phonemizer, dealing with language switch, so I'm adding the stresses on my todo list :)

Thank you a lot for pointing that out! It helps very much!
Have a good one!
