### ISSUE TITLE
Make package pip installable

### ISSUE THREAD

**Issue by patricebechard** [bootphon/phonemizer#27]
It would be great to make the package pip installable so that we don't have to clone the repo in order to use the package.

To clarify, I am able to install the package using `pip install .` from the root of the repo, but cannot find the package in pypi so that I could only install the package using `pip install phonemizer`.

Looking at the source code, it seems like everything is already in place so that this can be done (according to https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56)

**Comment by mmmaat** [comment]
Hi,
I setup the automatic upload to pypi: https://pypi.org/project/phonemizer, will be automatic on new releases.
