### ISSUE TITLE
multi phone for one word

### ISSUE THREAD

**Issue by lalimili6** [bootphon/phonemizer#28]
Hi is it possible that generate multi phones for one word?

**Comment by mmmaat** [comment]
Hi. I don't understand. Do you have an example of what you want?

**Comment by lalimili6** [comment]
for example in Persian(Farsi) we have the same words but different pronunciation like 
شکر
Sekar
Sokr

In English I think we have but I don't remember.

**Comment by mmmaat** [comment]
Ok I see. This is not possible because phonemizer is just a wrapper, in your case on espeak.
The text to phonemes rules for Farsi are [here](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/fa_rules).
