### ISSUE TITLE
add manual stress in a word?

### ISSUE THREAD

**Issue by vcjob** [bootphon/phonemizer#38]
Hello everyone! 

Want to pass a sentence in which multiple words have manual stress specified (e.g. "phonem'izer is a perf'ect tool!") where ' denotes stress position. Is it possible?

Thank you!

**Comment by mmmaat** [comment]
Hi,

No it is not possible actually. It could be interesting to add this as an option but I don't have time to implement that those days. But you can keep the stresses generated by the TTS backend with the `--with-stress` option:
```
echo "phonemizer is a perfect tool!" | phonemize --with-stress
fˈoʊnmaɪzɚɹ ɪz ɐ pˈɜːfɛkt tˈuːl
```

If you have an idea how to implement that I would welcome a pull request!

**Comment by vcjob** [comment]
> Hi,
> 
> No it is not possible actually. It could be interesting to add this as an option but I don't have time to implement that those days. But you can keep the stresses generated by the TTS backend with the `--with-stress` option:
> 
> ```
> echo "phonemizer is a perfect tool!" | phonemize --with-stress
> fˈoʊnmaɪzɚɹ ɪz ɐ pˈɜːfɛkt tˈuːl
> ```
> 
> If you have an idea how to implement that I would welcome a pull request!

Ok, got it. Will think about it
