### ISSUE TITLE
How to cite this repo?

### ISSUE THREAD

**Issue by LordOfLuck** [bootphon/phonemizer#41]
Hi guys, 

thank you for this amazing repo. I am using phonemizer in one of my projects and I would like to give credits in my corresponding paper. How would you like to be cited? Thanks

**Comment by mmmaat** [comment]
Hi, thanks ;) You can follow the link on [zenodo](https://doi.org/10.5281/zenodo.1045825) you'll find on the right panel a citation generator.

**Comment by LordOfLuck** [comment]
Alright, thank you. The issue can be closed.
