### ISSUE TITLE
shared memfd open() failed: Function not implemented

### ISSUE THREAD

**Issue by mwx2006** [bootphon/phonemizer#42]
echo "你好世界" | phonemize -l cmn -b espeak --with-stress
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented
[ERROR] shared memfd open() failed: Function not implemented
fatal error: espeak failed with return code 0

**Comment by mmmaat** [comment]
Hi,

You are using WSL (Windows Subsystem for Linux) right? If so this is WSL related bug, not a phonemizer one. Have a look [here](https://github.com/cypress-io/cypress/issues/4145) or [here](https://github.com/Microsoft/WSL/issues/3542)...

If you are using WSL version 1, you should try to update to version 2. Have a `wsl --list --verbose` to check version. See this [install tutorial](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install).

**Comment by mmmaat** [comment]
By the way

```
$ echo "你好世界" | phonemize -l cmn -b espeak --with-stress
nˈisa5n xˈɑusa5n s.ˈi.si̪5 tɕˈiɛsi̪5
```

**Comment by mwx2006** [comment]
OK
