### ISSUE TITLE
Running phonemizer on windows 7 failes

### ISSUE THREAD

**Issue by padmalcom** [bootphon/phonemizer#46]
Hi, I'm using phonemizer on windows 7 and python 3.6. Unfortunately, it can not detect my espeak installation. I installed to original binaries and added the installation path to my windows path variable. Furthermore, I installed espeak-ng.

The error is:
RuntimeError: espeak not installed on your system

**Comment by mmmaat** [comment]
Hi, did you see https://github.com/bootphon/phonemizer/issues/44 ?

**Comment by padmalcom** [comment]
No I did not, setting the variable to the exact exe path works, thank you!
