### ISSUE TITLE
Phonemizer gettiing stuck for some texts

### ISSUE THREAD

**Issue by singhaki** [bootphon/phonemizer#48]

**Comment by mmmaat** [comment]
Please give me some details if you want to receive any help. Version of phonemizer ? OS used ? backend used ? Concrete example ?

**Comment by singhaki** [comment]
sorry for no description
I was trying to phonemize some Indian languages texts in that I am facing an issue, it gets stuck while calling below function

function call phonemize("ఆడుకుంటున్న తన ఒక్కగానొక్క కొడుకును విగ్రహం వద్దకు తీసుకవచ్చి రూపధరుడు, కత్తిదూశాడు అతడు ఖడ్గంతో వేయబోయేసరికల్లా ఎవరో అతని చేయి పట్టుకొన్నట్టనిపించింది తలపైకెత్తి చూడగా పక్షులు మూడు లేవు వాటిస్థానే త్రిమూర్తులు నిలబడి వున్నారు మరుక్షణంలో వారూ అదృశ్యమైనారు మామూలురూపంలో మంత్రి దూరదర్శే తన చేయి పట్టుకుని ", backend='espeak', language="te") 
it does not happen for all language="te" texts
similarly for some mr( marathi )
phonemizer  version - 2.1
system - Ubuntu 18.04

**Comment by mmmaat** [comment]
I have no issues phonemizing that:
```
$ echo "ఆడుకుంటున్న తన ఒక్కగానొక్క కొడుకును విగ్రహం వద్దకు తీసుకవచ్చి రూపధరుడు, కత్తిదూశాడు అతడు ఖడ్గంతో వేయబోయేసరికల్లా ఎవరో అతని చేయి పట్టుకొన్నట్టనిపించింది తలపైకెత్తి చూడగా పక్షులు మూడు లేవు వాటిస్థానే త్రిమూర్తులు నిలబడి వున్నారు మరుక్షణంలో వారూ అదృశ్యమైనారు మామూలురూపంలో మంత్రి దూరదర్శే తన చేయి పట్టుకుని" | phonemize -b espeak -l te 
aːɖukunʈunna tana okkaɡaːnokka koɖukunu ʋiɡrahan ʋaddaku tiːsukaʋacci ruːpadʰaruɖu kattiduːɕaːɖu ataɖu kʰaɖɡantoː ʋeːjaboːjeːsarikallaː ʲeʋaroː atani ceːji paʈʈukonnaʈʈanipincindi talapaɪketti cuːɖaɡaː pakʂulu muːɖu leːʋu ʋaːʈistʰaːneː trimuːrtulu nilabaɖi ʋunnaːru marukʂaɳanloː ʋaːruː adruɕjamaɪnaːru maːmuːluruːpanloː mantri duːradarɕeː tana ceːji paʈʈukuni
```

This may be related to your espeak version (I am using espeak-ng-1.50):
```
$ phonemize --version
phonemizer-2.2
available backends: espeak-ng-1.50, espeak-mbrola, festival-2.5.0, segments-2.1.3
```
So I suggest you to try with the latest espeak-ng.

**Comment by singhaki** [comment]
which ubuntu you are using?

**Comment by mmmaat** [comment]
20.04

**Comment by singhaki** [comment]
it seems only espeak 1.50 is available for Ubuntu 20

**Comment by mmmaat** [comment]
you can compile it from source. See https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md#linux-mac-bsd

**Comment by singhaki** [comment]
Thanks!! it's working now.
