### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by alecristia** [bootphon/phonemizer#5]
# In mac
No instructions for festival installation in mac OS, instructions on http://www.festvox.org/docs/manual-2.4.0/festival_6.html#Installation not obvious to me.

Installation of espeak:
- download compiled version from http://espeak.sourceforge.net/download.html
- but what next? There is a "Notes-OSX.txt" at the top level and a ReadMe one level down in the downloaded and unzipped file, but neither indicates what the precise next step is (in fact the readme makes reference to a src directory which is not found in the unzipped folder)
- probably due to this, the wordseg tutorial call gives an error:
Alejandrinas-MacBook-Air:phonemizer acristia$ cat /Users/acristia/Documents/Providence_res/eth01_cds/eth01-ortholines.txt | phonemize --lang en-us -p " " -w ";eword "
Traceback (most recent call last):
  File "/anaconda/bin/phonemize", line 11, in <module>
    load_entry_point('phonemizer==0.3.1', 'console_scripts', 'phonemize')()
  File "build/bdist.macosx-10.7-x86_64/egg/phonemizer/main.py", line 145, in main
  File "build/bdist.macosx-10.7-x86_64/egg/phonemizer/main.py", line 73, in parse_args
  File "build/bdist.macosx-10.7-x86_64/egg/phonemizer/espeak.py", line 47, in supported_languages
  File "/anaconda/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/anaconda/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/anaconda/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

# On our oberon
[acristia@oberon phonemizer]$  python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/cm/shared/apps/python-anaconda/lib/python2.7/site-packages/test-easy-install-595.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /cm/shared/apps/python-anaconda/lib/python2.7/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  http://packages.python.org/distribute/easy_install.html

Please make the appropriate changes for your system and try again.

[acristia@oberon phonemizer]$ sudo python setup.py install
[sudo] password for acristia: 
acristia is not in the sudoers file.  This incident will be reported.

**Comment by mmmaat** [comment]
* On mac I don't know. 
* On oberon, phonemizer and wordseg are already installed:
  ```
  module load espeak festival python-anaconda
  source activate wordseg
  ```
* If you still want to install your own copy, try `python setup.py develop`.
* If the former failed, you need to install it in a virtual environment (create one with `conda create -n MYNAME; source activate MYNAME`). This will install it in `~/.conda/envs/...` where you have access.
