### ISSUE TITLE
Support for timing and TextGrid output

### ISSUE THREAD

**Issue by chen-deepdub** [bootphon/phonemizer#51]
Hi, Thank you for this great tool!

I wonder if you plan on supporting other output types like TextGrid that allow synchronization of phoneme and actual time. 
https://www.fon.hum.uva.nl/praat/manual/TextGrid_file_formats.html

**Comment by mmmaat** [comment]
Hi, this is actually not planned. It would be (theoretically) possible to extract time information from the espeak and festival backends but I never tried.

Moverover TextGrid support is beyond the scope of this tool. Assuming timing will be implemented some day it would be in a low level format closer to the actual text representation. You have great libs to deal with TextGrid (e.g. https://github.com/kylebgorman/textgrid/blob/master/textgrid/textgrid.py)

**Comment by chen-deepdub** [comment]
Thank you for your quick answer! 

My question was mainly about incorporating time information, TextGrid was brought up as a reference object that handles time intervals and other information nicely.

**Comment by mmmaat** [comment]
If you want to implement it by yourself and submit a pull request you are more than welcome :)
