### ISSUE TITLE
Don't know what phones belong to which word

### ISSUE THREAD

**Issue by RuABraun** [bootphon/phonemizer#56]
I wanted to get pronunciations for a vocab of 200k words, but after calling phonemizer the output is 199999 lines long. So I can't just paste the files, because that would lead to a mismatch.

I don't understand why the output does not have as the first column/field the word ?

**Comment by mmmaat** [comment]
(a hello or a thank you is always welcomed, I'm a human)

Hi,

* Are you sure you don't have an empty line in your output file? You should have one.
* If not this is a bug and I'll need more information : the exact command and parameters you used, the output of `phonemize --version` and, if you can find it, the missing word in output...

> I don't understand why the output does not have as the first column/field the word ?

We generally apply the phonemizer to whole sentences, not single words.

**Comment by mmmaat** [comment]
You should have an empty line because sometimes espeak (I'm supposing you're using espeak backend) drops words. In that case there is nothing we can do at phonemizer level, this is an espeak bug.

**Comment by RuABraun** [comment]
Sorry for being rude.

Thank you for the quick response, will respond tomorrow (just left work) with more information.
