### ISSUE TITLE
ImportError: No module named phonemizer.

### ISSUE THREAD

**Issue by ChrisChan2013** [bootphon/phonemizer#6]
I am installing facebookresearch/loop, and phonemizer is one of the modules should be imported. However, when I followed the whole installation of phonemizer and told me that finished processing dependencies for phonemizer==0.3.1, I got "ImportError: No module named phonemizer" when I was running the generate.py of voiceloop. I have no idea of why this happen.

**Comment by ChrisChan2013** [comment]
I installed Anaconda before. Does this matter?

**Comment by mmmaat** [comment]
Did you follow the [install procedure](https://github.com/bootphon/phonemizer#installation) ?

**Comment by mmmaat** [comment]
Ok sorry I read tour post a bit fast... If the installation succeeded but the import failed you may have a trouble with your conda virtual environment.

You can have a `conda env export -n YOUR_ENV_NAME` to see all the modules installed, you must have phonemizer and voiceloop. If you don't know YOUR_ENV_NAME, have a `conda env list`.

See the [conda doc](https://conda.io/docs/user-guide/tasks/manage-environments.html).
