### ISSUE TITLE
[ERROR] espeak-1.48.04: unrecognized option `--sep=_'

### ISSUE THREAD

**Issue by a-froghyar** [bootphon/phonemizer#64]
OS: OS X
phonemizer v2.2.2
python: 3.8
Backend: espeak

**Comment by mmmaat** [comment]
this is a espeak version issue, can I have `phonemize --version`?

**Comment by a-froghyar** [comment]
phonemizer-2.2.1, ah here might be the problem, I'll try to update to 2.2.2 with homebrew

**Comment by a-froghyar** [comment]
phonemizer-2.2.2
available backends: espeak-1.48.04, segments-2.2.0
uninstalled backends: espeak-mbrola, festival

**Comment by mmmaat** [comment]
maybe espeak-1.48.04... I test it against espeak-1.48.03.
Try to modify https://github.com/bootphon/phonemizer/blob/master/phonemizer/backend/espeak.py#L156 and let me know if it works

**Comment by mmmaat** [comment]
or even better, install espeak-ng. It usually give a better output...

**Comment by a-froghyar** [comment]
You were right, my brew installation of espeak-ng was acting up, `brew install espeak-ng` and then ` brew link --overwrite espeak-ng` did the trick, thanks for the quick replies!
