### ISSUE TITLE
"On Debian/Ubuntu simply run..." What about MacOS?

### ISSUE THREAD

**Issue by j-j-kam** [bootphon/phonemizer#67]
1. Can phonemizer be used on MacOs?
2. Can phonemizer synthesise sounds/words directly from IPA phonemes?

**Comment by mmmaat** [comment]
Hi,
1. Yes, you must install `espeak-ng` [from source](https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md#linux-mac-bsd) (or `espeak` is available as a [brew recipe](https://formulae.brew.sh/formula/espeak), phonemizer will work with it is an old version and it is better to use the latest espeak-ng version).
2. No, phonemizer is a text-to-phonemes tool. Maybe espeak is able to synthetize speech from phonemes, I'm not sure.
