### ISSUE TITLE
espeak: option '--ipa' doesn't allow an argument

### ISSUE THREAD

**Issue by yarekc** [bootphon/phonemizer#7]
`echo "bonjour le monde" | phonemize -l fr-fr`

gives: 

`espeak: option '--ipa' doesn't allow an argument`

**Comment by mmmaat** [comment]
This is probably an issue with the version of espeak you are using. Can you have a `phonemize --version` and let me know ? Alternatively you can install espeak-ng from here https://github.com/espeak-ng/espeak-ng/
