### ISSUE TITLE
[espeak] Phonemizer phonemize character '~' to 'tɪldə '

### ISSUE THREAD

**Issue by Ldoun** [bootphon/phonemizer#70]
Phonemizer phonemize character '~' to 'tɪldə '

Phonemizer version : 2.2.2
System: Window - Windows Subsystem for Linux

```phonemize('~',language='ko',backend='espeak',language_switch='remove-flags',preserve_punctuation=True)```

charater '~' can't be pronounced so I think it is wise to delete this character if it was given as input

**Comment by mmmaat** [comment]
Hi, this is the normal behavior of espeak when it encounters isolated marks to "pronounce" them... You have two solutions.
1. Filter out those marks from the input
2. Configure the `punctuation_marks` argument to keep those marks unprocessed: 

```python
>>> phonemize('~',language='ko',backend='espeak',language_switch='remove-flags',preserve_punctuation=True, punctuation_marks='~') 
'~'
```

**Comment by Ldoun** [comment]
okay got it~
thanks for the reply
