### ISSUE TITLE
Train phonemizer for new languages

### ISSUE THREAD

**Issue by AASHISHAG** [bootphon/phonemizer#71]
Hello team, thank you for making the code open-source.
I want to check if we can train phonemizer for new languages? Looking forward to your help. Thank you.

**Comment by mmmaat** [comment]
Hi,
No you cannot. Phonemizer depends on backends for the phonemization. You can try a [morphene to phoneme mapping](https://github.com/bootphon/phonemizer/tree/master/phonemizer/share/segments) for the Segment backend, or [add a language](https://github.com/espeak-ng/espeak-ng/blob/master/docs/add_language.md) to the espeak-ng backend...
