### ISSUE TITLE
please add tie bars

### ISSUE THREAD

**Issue by martino-vic** [bootphon/phonemizer#74]
espeak-ng allows you to add tie bars to the output, see: https://github.com/espeak-ng/espeak-ng/issues/1002
However, phonemizer doesn't seem to offer a parameter with which to make use of that function. Is there a way to add tie bars?

**Comment by mmmaat** [comment]
Hi, OK this is a useful feature to add. I'm working on a fix with it. In the while, you can add the `--tie` option to https://github.com/bootphon/phonemizer/blob/master/phonemizer/backend/espeak.py#L240. This is dirty but should work.

**Comment by mmmaat** [comment]
done ;)

**Comment by martino-vic** [comment]
Thank you so much!
