### ISSUE TITLE
Decoder - Convert phoneme sequence back to string

### ISSUE THREAD

**Issue by patrickvonplaten** [bootphon/phonemizer#83]
**Is your feature request related to a problem? Please describe.**
I'm looking for a tool that let's one convert a sequence of phonemes back to text. E.g. when training a speech recognition model, one usually converts a sentence to a phoneme sequence, then trains the model, and then it would be nice to be able to re-convert the phoneme sequence back to the sentence. Is this maybe possible?

**Comment by mmmaat** [comment]
This would be really interesting -- you're not the first one asking for such a feature -- but this is out-of-scope for the phonemizer. It is basically a wrapper on TTS software (espeak and festival) and there actually no way to convert the phonemes back to text...
