### ISSUE TITLE
Problems about Mandarin phoneme

### ISSUE THREAD

**Issue by mynah15** [bootphon/phonemizer#90]
When run phonemize with -l cmn or zh, the phoneme is International Phonetic Alphabet  instead of Mandarin phoneme

Is this a code problem or a bug?
How can i convert Chinese to Mandarin phoneme?
Look forward to your reply, thanks!

**Expected behavior**
 I try to convert Chinese to Mandarin phoneme with this code：

cat chinese.txt | PHONEMIZER_ESPEAK_PATH=$(which espeak) phonemize -o train_out.phn -p ' ' -w '' -l zh  -j 70 --language-switch remove-flags

result:
fatal error: language "zh" is not supported by the espeak backend
then i check:
espeak --voices  it include  Mandarin
phonemize  --list-languages  it said：cmn ->	Chinese (Mandarin)

**Phonemizer version**
phonemizer-3.0
espeak-ng-1.50, espeak-mbrola, festival-2.5.0, segments-2.2.0

**System**
ubuntu 20.04

**Comment by mmmaat** [comment]
Hi, if you use phonemizer with the `cmn` language flag do you have the result you expect? This is possible that "zh" for espeak is viewed as "cmn" by phonemizer (because of [that](https://github.com/bootphon/phonemizer/blob/7088b9314dcdb97adcf03eba89c4d9b411c8f701/phonemizer/backend/espeak/api.py#L158)).

Finally I don't know what is the Mandarin phoneme set you are expecting, is it different from IPA? If so, you cannot get here because espeak (and so phonemizer) only outputs IPA phonemes.

**Comment by YoungKang1222** [comment]
> 

hi，I wonder what' s the content of your "chinese.txt"? Is it piyin(ni3 hao3) or character(你好)?

And this is my example:
![image](https://user-images.githubusercontent.com/30460985/143978703-c9afb364-12c6-4683-ac41-34f0be10ad8a.png)

**Comment by YoungKang1222** [comment]
> > 
> 
> hi，I wonder what' s the content of your input. Is it piyin(ni3 hao3) or character(你好)?
> 
> And this is my example: ![image](https://user-images.githubusercontent.com/30460985/143978703-c9afb364-12c6-4683-ac41-34f0be10ad8a.png)


![image](https://user-images.githubusercontent.com/30460985/143982298-62e7106d-f909-41a0-a905-9982ae1ee3b1.png)

**Comment by mynah15** [comment]
> Hi, if you use phonemizer with the `cmn` language flag do you have the result you expect? This is possible that "zh" for espeak is viewed as "cmn" by phonemizer (because of [that](https://github.com/bootphon/phonemizer/blob/7088b9314dcdb97adcf03eba89c4d9b411c8f701/phonemizer/backend/espeak/api.py#L158)).
> 
> Finally I don't know what is the Mandarin phoneme set you are expecting, is it different from IPA? If so, you cannot get here because espeak (and so phonemizer) only outputs IPA phonemes.

Thanks for your help！Mandarin phoneme is the basic unit of pronunciation，can be used for training HMM-GMM model, the pronunciation sounds like IPA but not exactly the same. So use the IPA pronunciation sounds like dialect and even hard to understand. I found the code（cat chinese.txt | PHONEMIZER...） on the Internet，some one got the desired result, and said phonemize worked very well. As you said if espeak and phonemizer only outputs IPA phonemes, I may not get the right result in this way.

**Comment by mynah15** [comment]
> > hi，I wonder what' s the content of your input. Is it piyin(ni3 hao3) or character(你好)?
> > And this is my example:
> 
> ![image](https://user-images.githubusercontent.com/30460985/143982298-62e7106d-f909-41a0-a905-9982ae1ee3b1.png)
> 
> which one is correct if i only need to get the position of a phone?

Thank you for your reply， I try to input character(你好), hope to get phoneme, eg(你好 --> n i3 h ao3). The pinyin(ni3 hao3)is different form phoneme, because phoneme is the basic unit of pronunciation，and pinyin is the combination of phonemes.
Take an inappropriate example， hello phonetic symbol is [həˈləʊ] phoneme seems like [h  ə1  l  əʊ5]
On the Internet，some one got the desired result, I try to use his code (cat chinese.txt | PHONEMIZER....) but it did not compile successfully. Do you know how to get the correct phoneme? Thanks.

**Comment by mmmaat** [comment]
Maybe the source where you fount this exemple on Internet explains which version of the phonemizer they use? You could try with [phonemizer-2.2.2](https://github.com/bootphon/phonemizer/releases/tag/v2.2.2), as the 3.0 changed a lot of things. This is not unlikely that the `cmn`/`zh` difference comes from that.

**Comment by mynah15** [comment]
> Maybe the source where you fount this exemple on Internet explains which version of the phonemizer they use? You could try with [phonemizer-2.2.2](https://github.com/bootphon/phonemizer/releases/tag/v2.2.2), as the 3.0 changed a lot of things. This is not unlikely that the `cmn`/`zh` difference comes from that.

Thanks, I can't find information about the version of the phonemizer they use
I will try to use different version phonemize and espeak.
